# Jekyll configuration for Red Storm Tools Suite
# This enables proper asset handling for GitHub Pages

# Site settings
title: Red Storm Tools Suite
description: Order of Battle Generator for Red Storm tabletop wargame

# Build settings
markdown: kramdown
highlighter: rouge

# Plugin settings
plugins:
  - jekyll-relative-links

# Relative links settings
relative_links:
  enabled: true
  collections: true

# Asset optimization
sass:
  style: compressed

# GitHub Pages settings
github: [metadata]